### ISSUE TITLE
Lua error, change maps option does nothing.

### ISSUE THREAD

**Issue by Eremeir** [p3lim-wow/InteractiveWormholes#71]
**Describe the bug**
`5x ...ns/InteractiveWormholes/libs/Dashi/modules/event.lua:121: ...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:50: bad argument #1 to 'GetMapArtID' (Usage: local uiMapArtID = C_Map.GetMapArtID(uiMapID))
[string "=[C]"]: in function `error'
[string "@InteractiveWormholes/libs/Dashi/modules/event.lua"]:121: in function `TriggerEvent'
[string "@InteractiveWormholes/libs/Dashi/modules/event.lua"]:132: in function <...ns/InteractiveWormholes/libs/Dashi/modules/event.lua:131>`

Locals:
(*temporary) = "...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:50: bad argument #1 to 'GetMapArtID' (Usage: local uiMapArtID = C_Map.GetMapArtID(uiMapID))"

Even on the newest release, wormholes do not open the applicable world map when used and require manual navigation, this does not change whether "Change Maps" is ticked on or off in the options.

**How to reproduce**
Tested with all addons disabled except for Bugsack and Interactive Wormholes on a fresh UI reload.
This happens with all wormhole items, but it's easiest to test with Manapoof.

**What did you expect?**
Interacting with a wormhole should directly open the map that wormhole is attached to, at least when the Change Maps options is enabled.

**Comment by p3lim** [comment]
Auto-changing maps is a hot broken mess, partly from the LCA algorithm implementation by me, but mostly because of how the world map works and how easy it is to taint and break it.

This is probably not going to improve until blizzard either improves their map implementation or implements an API to change the map in a safe way.

The compromise right now is to just attach the pins to the map and let the player navigate to them manually, which is obviously not the best way to go about it, but that's the only safe way right now.
